CREATE OR REPLACE PROCEDURE SP_ALLINEA_SEQUENCE AUTHID CURRENT_USER AS
  V_NOMETABLE VARCHAR2(80);
  v_NOMEPK VARCHAR2(80);
  v_MAXVAL NUMBER(9);
  v_COUNT_PK NUMBER(9);
 BEGIN

  DECLARE CURSOR CUR_SEQ IS
    SELECT SEQUENCE_NAME
     FROM USER_SEQUENCES
     where SEQUENCE_NAME = 'LNK_LINK_MID';

  BEGIN FOR SEQ IN CUR_SEQ LOOP
     v_NOMETABLE := SUBSTR(SEQ.SEQUENCE_NAME, 4);

  BEGIN
     SELECT COUNT(C.COLUMN_NAME)
     INTO v_COUNT_PK
     FROM USER_CONSTRAINTS T,
          USER_CONS_COLUMNS C,
          USER_TAB_COLUMNS A
     WHERE  T.TABLE_NAME = v_NOMETABLE
     AND T.CONSTRAINT_TYPE = 'P'
     AND T.OWNER = C.OWNER
     AND T.CONSTRAINT_NAME = C.CONSTRAINT_NAME
     AND C.TABLE_NAME = A.TABLE_NAME
     AND C.COLUMN_NAME = A.COLUMN_NAME
     AND A.DATA_TYPE = 'NUMBER';

    if (v_COUNT_PK = 1) THEN

                   SELECT C.COLUMN_NAME
                      INTO v_NOMEPK
                   FROM USER_CONSTRAINTS T,
                        USER_CONS_COLUMNS C,
                        USER_TAB_COLUMNS A
                   WHERE  T.TABLE_NAME = v_NOMETABLE
                   AND T.CONSTRAINT_TYPE = 'P'
                   AND T.OWNER = C.OWNER
                   AND T.CONSTRAINT_NAME = C.CONSTRAINT_NAME
                   AND C.TABLE_NAME = A.TABLE_NAME
                   AND C.COLUMN_NAME = A.COLUMN_NAME
                   AND A.DATA_TYPE = 'NUMBER';

                    EXECUTE IMMEDIATE ' SELECT NVL(MAX("' || v_NOMEPK || '"), 0) FROM '|| v_NOMETABLE  INTO v_MAXVAL;

                    IF(v_MAXVAL > 0 AND v_MAXVAL IS NOT NULL) THEN
                      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || SEQ.SEQUENCE_NAME;
                      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || SEQ.SEQUENCE_NAME || ' START WITH '|| TO_CHAR(v_MAXVAL + 1) ||' MAXVALUE 999999999999999999999999999  MINVALUE 1  NOCYCLE  NOCACHE  NOORDER';

                           ELSE
                      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || SEQ.SEQUENCE_NAME;
                      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || SEQ.SEQUENCE_NAME || ' START WITH 1 MAXVALUE 999999999999999999999999999  MINVALUE 1  NOCYCLE  NOCACHE  NOORDER';

                    END IF;


    END IF;
    EXCEPTION
                             WHEN NO_DATA_FOUND THEN NULL;
                             WHEN TOO_MANY_ROWS THEN DBMS_OUTPUT.PUT_LINE('SEQ_' || v_NOMETABLE || ' non aggiornata');
 END;

  END LOOP; END;

 COMMIT;
END;
/
