/* Formatted on 14/03/2016 11:45:36 (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW API_MSG_DETAILS
(
   MID,
   LANG,
   DAT_CREAZ,
   FLG_PP,
   FLG_ISNEW,
   FLG_PREFER,
   CATEGORIA,
   TITOLO,
   TESTO
)
AS
   SELECT A.MID AS MID,
          B.LN_CODE AS LANG,
          DATA_INS,
          DECODE (UPPER (FLG_PRIMO), 'S', 1, 0) AS FLG_PP,
          CASE
             WHEN NUM_VISIBILITA > NUM_LETTURE THEN 1
             ELSE CASE WHEN FLG_READ = 1 THEN 1 ELSE 0 END
          END
             AS FLG_ISNEW,
          DECODE (UPPER (FLG_PREFERITI), 'S', 1, 0) AS FLG_PREFER,
          NVL (DES_CATEGORIA, 'Altro') AS CATEGORIA,
          DES_TITOLO AS TITOLO,
          DES_TESTO AS TESTO
     FROM MSG_MESSAGE A JOIN MSG_MESSAGE_LN B ON A.MID = B.MID
    WHERE UPPER (FLG_CANC) = 'N';
