/* Formatted on 14/03/2016 11:45:33 (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW API_CC_AD
(
   MID,
   LANG,
   CURRICULUM,
   COURSE,
   DESCRIPTION,
   METODI_DID_DES,
   OBIETT_FORM_DES,
   PREREQUISITI_DES,
   CONTENUTI_DES,
   TESTI_RIF_DES,
   MOD_VER_APPR_DES,
   ALTRE_INFO_DES,
   CREDITS_DES,
   CREDITS
)
AS
   SELECT A.MID,
          A.LN_CODE AS LANG,
          A.PERCORSO AS CURRICULUM,
          A.ATTIVITA AS COURSE,
          A.DESCRIZIONE AS DESCRIPTION,
          A.METODI_DID_DES,
          A.OBIETT_FORM_DES,
          A.PREREQUISITI_DES,
          A.CONTENUTI_DES,
          A.TESTI_RIF_DES,
          A.MOD_VER_APPR_DES,
          A.ALTRE_INFO_DES,
          A.STRUTTURA_CFU AS CREDITS_DES,
          b.peso CREDITS
     FROM GOL_AD_LN a JOIN GOL_AD b ON a.mid = b.mid;
